---
name: Binary Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & Release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: "README.md LICENSE"
